"""add statement_files table

Revision ID: 0a1430f21d66
Revises: 60f2323257db
Create Date: 2025-12-26 16:24:06.126314

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a1430f21d66"
down_revision: Union[str, None] = "60f2323257db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "statement_files",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("stored_filename", sa.String(length=255), nullable=False),
        sa.Column("stored_path", sa.String(length=512), nullable=False),
        sa.Column(
            "format",
            sa.Enum("CSV", name="statementformat", native_enum=False),
            nullable=False,
        ),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("columns", sa.JSON(), nullable=True),
        sa.Column("date_from", sa.Date(), nullable=True),
        sa.Column("date_to", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("UPLOADED", name="statementstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("is_ingested", sa.Boolean(), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "account_id", "content_hash", name="uq_statement_account_hash"
        ),
    )
    op.create_index(
        "ix_statement_account_created",
        "statement_files",
        ["account_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_statement_files_account_id"),
        "statement_files",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_statement_files_id"), "statement_files", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_statement_files_id"), table_name="statement_files")
    op.drop_index(op.f("ix_statement_files_account_id"), table_name="statement_files")
    op.drop_index("ix_statement_account_created", table_name="statement_files")
    op.drop_table("statement_files")
    # ### end Alembic commands ###
