"""add datelock_to to accounts

Revision ID: 8ea4075a28e2
Revises: 0a1430f21d66
Create Date: 2025-12-26 19:54:59.905138

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8ea4075a28e2"
down_revision: Union[str, None] = "0a1430f21d66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("datelock_to", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "datelock_to")
    # ### end Alembic commands ###
