"""create transactions table

Revision ID: af4e2044a3bb
Revises: be9c3b99c92e
Create Date: 2025-12-26 20:19:24.904187

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "af4e2044a3bb"
down_revision: Union[str, None] = "be9c3b99c92e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("statement_file_id", sa.UUID(), nullable=False),
        sa.Column("row_id", sa.Integer(), nullable=False),
        sa.Column(
            "ingested_content", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("transaction_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "computed_content", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("computed_content_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "inserted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["statement_file_id"], ["statement_files.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "statement_file_id", "row_id", name="uq_transaction_statement_row"
        ),
    )
    op.create_index(
        "ix_transaction_account_inserted",
        "transactions",
        ["account_id", "inserted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_account_id"), "transactions", ["account_id"], unique=False
    )
    op.create_index(op.f("ix_transactions_id"), "transactions", ["id"], unique=False)
    op.create_index(
        op.f("ix_transactions_statement_file_id"),
        "transactions",
        ["statement_file_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_transaction_hash"),
        "transactions",
        ["transaction_hash"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_transaction_hash"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_statement_file_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_account_id"), table_name="transactions")
    op.drop_index("ix_transaction_account_inserted", table_name="transactions")
    op.drop_table("transactions")
    # ### end Alembic commands ###
