"""add StatementFile extensions: ingested_rows_count, ingestion_errors_count, date_column

Revision ID: be9c3b99c92e
Revises: 8ea4075a28e2
Create Date: 2025-12-26 20:07:33.878410

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "be9c3b99c92e"
down_revision: Union[str, None] = "8ea4075a28e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "statement_files",
        sa.Column(
            "ingested_rows_count", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "statement_files",
        sa.Column(
            "ingestion_errors_count", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "statement_files",
        sa.Column("date_column", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("statement_files", "date_column")
    op.drop_column("statement_files", "ingestion_errors_count")
    op.drop_column("statement_files", "ingested_rows_count")
    # ### end Alembic commands ###
